export const REGIONS: { [key: string]: string } = {
  kyivska: "Київська",
  khmelnytska: "Хмельницька",
  cherkaska: "Черкаська",
  chernihivska: "Чернігівська",
  chernivetska: "Чернівецька",
  crimea: "АР Крим",
  dnipropetrovska: "Дніпропетровська",
  donetska: "Донецька",
  ivano_frankivska: "Івано-Франківська",
  kharkivska: "Харківська",
  khersonska: "Херсонська",
  kirovohradska: "Кіровоградська",
  luhanska: "Луганська",
  lvivska: "Львівська",
  mykolaivska: "Миколаївська",
  odeska: "Одеська",
  poltavska: "Полтавська",
  rivnenska: "Рівненська",
  sumska: "Сумська",
  ternopilska: "Тернопільська",
  vinnytska: "Вінницька",
  volynska: "Волинська",
  zakarpatska: "Закарпатська",
  zhytomyrska: "Житомирська",
};
